version: 2

jobs:
  plan-apply:
    working_directory: /tf-SageMaker-ML_MODEL_EndPointConfig_Endpoints
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            terraform init 
            terraform plan 
      - persist_to_workspace:
          root: .
          paths:
            - .