---
# https://circleci.com/developer/orbs/orb/circleci/terraform
version: '2.1'
orbs:
  terraform: circleci/terraform@2.1.0
workflows:
  deploy_infra:
    jobs:
    - terraform/fmt:
          checkout: true
          context: myfreeawsaccess
    - terraform/validate:
        checkout: true
        context: myfreeawsaccess 
    - terraform/plan:
        checkout: true
        context: myfreeawsaccess
        persist-workspace: true
        requires:
        - terraform/validate
    - terraform/apply:
        attach-workspace: true
        context: myfreeawsaccess
        filters:
          branches:
            only: main
        requires:
          - terraform/plan
#          - hold-apply