version: 2.1
executors:
  terraform:
    docker:
      - image: hashicorp/terraform:0.14.2
    working_directory: ~/tf_sagemaker-circleci/tf-SageMaker-ML_NOTEBOOK

jobs:
  build:
    executor: terraform
    steps:
      - checkout:  
          path: ~/tf_sagemaker-circleci
      - run: ls -la; pwd;    
      - run: apk update && apk add bash
#      - run: mkdir plan
      - run: terraform init
#      - run: terraform workspace select $STAGE
#      - run: .circleci/gateway_deployment.sh
      - run: terraform plan 
      - persist_to_workspace:
          root: . 
          paths:
             - .
#            - plan
  deploy:
    executor: terraform
    steps:
      - checkout
#          path: ~/tf_sagemaker-circleci
#      - run: ls -la; pwd;  
      - run: apk update && apk add bash
      - attach_workspace:
          at: ~/tf_sagemaker-circleci/tf-SageMaker-ML_NOTEBOOK/
#      - run: terraform init
#      - run: terraform workspace select $STAGE
      - run: terraform apply -auto-approve
#      - run: .circleci/gateway_deployment.sh

workflows:
  version: 2
  build-only:
    jobs:
      - build:
          context: myfreeawsaccess
          filters:
            branches:
              ignore:
                - main
  build-and-deploy-dev:
    jobs:
      - build:
          context: myfreeawsaccess
          filters:
              branches:
                only:
                  - main
      - deploy:
          context: myfreeawsaccess
          requires:
            - build
          filters:
            branches:
              only:
                - main
  